#!/bin/sh

PROJECT_DIR=/var/www/trac/EventSpiral

trac-admin $PROJECT_DIR milestone remove 'milestone1'
trac-admin $PROJECT_DIR milestone remove 'milestone2'
trac-admin $PROJECT_DIR milestone remove 'milestone3'
trac-admin $PROJECT_DIR milestone remove 'milestone4'
trac-admin $PROJECT_DIR milestone remove 'milestone4'

trac-admin $PROJECT_DIR component remove 'component1'
trac-admin $PROJECT_DIR component remove 'component2'

trac-admin $PROJECT_DIR version remove '2.0'
trac-admin $PROJECT_DIR version remove '1.0'

trac-admin $PROJECT_DIR priority remove 'blocker'
trac-admin $PROJECT_DIR priority remove 'critical'
trac-admin $PROJECT_DIR priority remove 'major'
trac-admin $PROJECT_DIR priority remove 'minor'
trac-admin $PROJECT_DIR priority remove 'trivial'

trac-admin $PROJECT_DIR ticket_type remove 'defect'
trac-admin $PROJECT_DIR ticket_type remove 'enhancement'
trac-admin $PROJECT_DIR ticket_type remove 'task'

trac-admin $PROJECT_DIR resolution remove 'wontfix'
trac-admin $PROJECT_DIR resolution remove 'duplicate'
trac-admin $PROJECT_DIR resolution remove 'worksforme'

################################################################################

env LANG=ja_JP.UTF-8 trac-admin $PROJECT_DIR ticket_type add '作成（ソースコード）'
env LANG=ja_JP.UTF-8 trac-admin $PROJECT_DIR ticket_type add 'バグ修正（ソースコード）'
env LANG=ja_JP.UTF-8 trac-admin $PROJECT_DIR ticket_type add '作成（単体テスト）'
env LANG=ja_JP.UTF-8 trac-admin $PROJECT_DIR ticket_type add 'バグ修正（単体テスト）'
env LANG=ja_JP.UTF-8 trac-admin $PROJECT_DIR ticket_type add 'レビュー'
env LANG=ja_JP.UTF-8 trac-admin $PROJECT_DIR ticket_type add '作成（結合テスト）'
env LANG=ja_JP.UTF-8 trac-admin $PROJECT_DIR ticket_type add 'バグ修正（結合テスト）'
env LANG=ja_JP.UTF-8 trac-admin $PROJECT_DIR ticket_type add '結合テスト'
env LANG=ja_JP.UTF-8 trac-admin $PROJECT_DIR ticket_type add 'その他'

trac-admin $PROJECT_DIR component add 'dwr.xml' ''
trac-admin $PROJECT_DIR component add 'index.html' ''
trac-admin $PROJECT_DIR component add 'DisplayEventListController.java' ''
trac-admin $PROJECT_DIR component add 'SearchingForm.java' ''
trac-admin $PROJECT_DIR component add 'EventDetailSearchResultEntity.java' ''
trac-admin $PROJECT_DIR component add 'EventDetailEntity.java' ''
trac-admin $PROJECT_DIR component add 'EventModel.java' ''
trac-admin $PROJECT_DIR component add 'Event.java' ''
trac-admin $PROJECT_DIR component add 'UC[DisplayEventList]' ''
trac-admin $PROJECT_DIR component add 'eventDetail.html' ''
trac-admin $PROJECT_DIR component add 'registerEvent.html' ''
trac-admin $PROJECT_DIR component add 'registeredEventList.html' ''
trac-admin $PROJECT_DIR component add 'boughtTicketList.html' ''
trac-admin $PROJECT_DIR component add 'signupPromoter.html' ''
trac-admin $PROJECT_DIR component add 'IdentifyingEventForm.java' ''
trac-admin $PROJECT_DIR component add 'RegisteringEventForm.java' ''
trac-admin $PROJECT_DIR component add 'RegisteringSeatCategoryForm.java' ''
trac-admin $PROJECT_DIR component add 'BuyingTicketForm.java' ''
trac-admin $PROJECT_DIR component add 'CancelingTicketForm.java' ''
trac-admin $PROJECT_DIR component add 'IdentifyingAccountForm.java' ''
trac-admin $PROJECT_DIR component add 'EventInfoEntity.java' ''
trac-admin $PROJECT_DIR component add 'TicketGroupSearchResultEntity.java' ''
trac-admin $PROJECT_DIR component add 'TicketGroupEntity.java' ''
trac-admin $PROJECT_DIR component add 'DisplayEventDetailController.java' ''
trac-admin $PROJECT_DIR component add 'RegisterEventController.java' ''
trac-admin $PROJECT_DIR component add 'RegisterSeatCategoryController.java' ''
trac-admin $PROJECT_DIR component add 'DisplayRegisteredEventListController.java' ''
trac-admin $PROJECT_DIR component add 'DeleteEventController.java' ''
trac-admin $PROJECT_DIR component add 'BuyTicketController.java' ''
trac-admin $PROJECT_DIR component add 'DisplayBoughtTicketListController.java' ''
trac-admin $PROJECT_DIR component add 'CancelTicketController.java' ''
trac-admin $PROJECT_DIR component add 'SignUpPromotorController.java' ''
trac-admin $PROJECT_DIR component add 'SeatCategory.java' ''
trac-admin $PROJECT_DIR component add 'TicketGroup.java' ''
trac-admin $PROJECT_DIR component add 'TicketModel.java' ''
trac-admin $PROJECT_DIR component add 'AccountModel.java' ''
trac-admin $PROJECT_DIR component add 'UC[DisplayEventDetail]' ''
trac-admin $PROJECT_DIR component add 'UC[RegisterEvent]' ''
trac-admin $PROJECT_DIR component add 'UC[RegisterSeatCategory]' ''
trac-admin $PROJECT_DIR component add 'UC[DisplayRegisteredEventList]' ''
trac-admin $PROJECT_DIR component add 'UC[DeleteEvent]' ''
trac-admin $PROJECT_DIR component add 'UC[BuyTicket]' ''
trac-admin $PROJECT_DIR component add 'UC[DisplayBoughtTicketList]' ''
trac-admin $PROJECT_DIR component add 'UC[CancelTicket]' ''
trac-admin $PROJECT_DIR component add 'UC[SighUpPromoter]' ''
trac-admin $PROJECT_DIR component add 'Ticket.java' ''
trac-admin $PROJECT_DIR component add 'SeatCategoryEntity.java' ''
env LANG=ja_JP.UTF-8 trac-admin $PROJECT_DIR component add 'その他' ''

trac-admin $PROJECT_DIR milestone add 'preSprint'
trac-admin $PROJECT_DIR milestone add 'Sprint1st'
trac-admin $PROJECT_DIR milestone add 'Sprint2nd'
trac-admin $PROJECT_DIR milestone add 'Sprint3rd'
trac-admin $PROJECT_DIR milestone add 'Sprint4th'

exit 0
